[package]
name = "pz-pack-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0" }
clap = { version = "4.6.6", features = ["derive"] }
fs-err = { version = "3.3.1" }
glam = { version = "0.33.3", features = ["serde"] }
indexmap = { version = "2.14.0", features = ["serde"] }
pz-pack = { path = "../pz-pack" }
serde = { version = "1.0", features = ["derive"] }
toml = { version = "1.1.4" }
